### ISSUE TITLE
Controlling size of github and twitter icons

### ISSUE THREAD

**Issue by antortjim** [sylvaindurand/jekyll-multilingual#10]
I just replicated your code to make jekyll multilingual sites on Github and it works like a charm! Thanks. However I am having a little issue concerning the size of the logos. For some reason they appear gigantic. How can I control their size and, why wouldn't they appear identical to how they look like in your website??

You can visit my repo here https://github.com/antortjim/antortjim.github.io
I am using Jekyll 3.2.1

Thanks in advance / Merci :)

**Comment by fenollp** [comment]
That's fixable with some CSS ;)

**Comment by antortjim** [comment]
Sure! I don't know how to do it though. It's a bit tricky. I have looked for the difference that could cause this for a while and I can't find it. Could you provide the required css? It should be specified in the main.scss file I guess

**Comment by antortjim** [comment]
I just fixed it. I just had to remove the .svg files living in _includes/ so that the default ones are loaded instead :)
