### ISSUE TITLE
Question: what do you think about implementing my dates localisation include ?

### ISSUE THREAD

**Issue by oncleben31** [sylvaindurand/jekyll-multilingual#12]
By working on the i18n of my blog using Jekyll/minima, I've write an include allowing to translate the dates using the standard format syntax.
I know you have suggest a specific include to manage the ordinalized days.
My include don't cover this case but cover all the date formats using `%a` (abbreviated day name), `%A` (full day name), `%b` (abbreviated month name) and `%B` (full month name) syntax.

Are you interested if I make a PR with the implementation in your example ?

You can look at the code at: https://github.com/oncleben31/jekyll-date-basic-i18n

**Comment by sylvaindurand** [comment]
It looks great!
I probably need to update this repo, but any PR is welcome!
