### ISSUE TITLE
Accept-Language header.

### ISSUE THREAD

**Issue by aensidhe** [sylvaindurand/jekyll-multilingual#15]
Hello.

Thank you for great work. Is there any way to select a default language for default page of blog based on Accept-Language header?

I could find any options for that on web.

Thank you.

**Comment by sylvaindurand** [comment]
Probably, but it is clearly something to do with your web server. 
You need to ask him: "if accept-language is x, take this page instead". 

In nginx, here is a way to do it: https://stackoverflow.com/questions/3657614/how-to-rewrite-location-in-nginx-depending-on-the-client-browsers-language
You could generate a configuration file with Jekyll, then include it in nginx.
But it would probably forbid users to choose their language.
