### ISSUE TITLE
How to delete redundancy in Liquid 4?

### ISSUE THREAD

**Issue by marcphilipp** [sylvaindurand/jekyll-multilingual#16]
Hi Sylvain,

thanks for a great blog post and sharing this example code base! In your article you wrote

> It will be possible to delete this redundancy when Jekyll will use Liquid 4.

What did you mean by that? Is it somehow possible to iterate over all pages _and_ posts in a single loop in Liquid 4?

**Comment by a1ip** [comment]
Interested the same question

**Comment by sylvaindurand** [comment]
Yes, but I didn't try!
https://shopify.github.io/liquid/filters/concat/
I should be possible since Jekyll 3.5, which use Jekyll 4 ;)
