### ISSUE TITLE
how does one handle a multi domain situation?

### ISSUE THREAD

**Issue by gideondsouza** [sylvaindurand/jekyll-multilingual#18]
hi,

Just like the author, she/he has a two domains https://www.sylvaindurand.org  and https://www.sylvaindurand.fr

This is exactly what I have and I would want to build the same sort of system between my  gideondsouza.com and gideondsouza.de (soon to be translated)

from the code in this article : https://www.sylvaindurand.org/making-jekyll-multilingual/

I don't see how this code would work : `<a href="{{ post.url }}">{{ post.title }}</a>` how would it manage to capture url from two different domains?

**Comment by rth** [comment]
That's a good question.

I imagine this could be done with URL rewrites (see e.g. this [SO question](https://stackoverflow.com/questions/18153189/how-to-root-multiple-domains-to-multiple-subfolders)) I wonder it there is a pure jekyll solution..  Would have any suggestions @sylvaindurand ?

**Comment by sylvaindurand** [comment]
It is a pure Jekyll solution ;) 

In `_data/translation.yml`, I simply stored the two domains:
```
en:
  base: "https://www.sylvaindurand.org"

fr:
  base: "https://www.sylvaindurand.fr"
```

It allows me to use `{{ site.data.translations[lang].base }}` in my layout.

**Comment by sylvaindurand** [comment]
In addition: if you want to cleanly redirect to the good domain (each article in French can be seen on the .fr domain only), you need to tweak things a little.

I use (and recommand) *nginx*, which use simple configuration files. 

I use *Jekyll* to create a configuration file (the same for the two languages): 
```
---
layout:
lang: fr
permalink: /fr.conf
---
{% for post in site.posts %}{% if post.lang != page.lang and post.url != '/' and post.url != '/journal/' %}
location '{{ post.url }}' {
  return 301 {{ site.data.translations[post.lang].base }}{{ post.url | replace: "/journal/", "/" }};
}
{% endif %}
``` 

... then I include this .conf file in my nginx configuration file.
I hope it helps!

**Comment by rth** [comment]
Thanks a lot for the additional details @sylvaindurand !

**Comment by sylvaindurand** [comment]
Quite late... I'm on another project far from Github and it takes all my spare time ;)
