### ISSUE TITLE
<html lang="{{ page.lang }}">

### ISSUE THREAD

**Issue by akira-okumura** [sylvaindurand/jekyll-multilingual#19]
Hi,

Thank you very much for the nice multilingual example, which helped me a lot.

In `_layouts/default.html`, `lang` setting is missing, resulting in language confusion by browsers. In my case my Japanese website was regarded as Chinese pages, and so Chinese characters were used to display my website. This happens because of the fact that Japanese and Chinese languages have slightly different-shape character set.

Changing `<html>` in `'_layouts/default.html` to `<html lang="{{ page.lang }}">` fixes this issue.

**Comment by sylvaindurand** [comment]
I just fixed it, thanks!
