### ISSUE TITLE
Release theme as a gem

### ISSUE THREAD

**Issue by DirtyF** [sylvaindurand/jekyll-multilingual#2]
Bonjour Sylvain,

A first support for themes just landed in jekyll/master, do you plan to test it and release this theme as a gem?

**Comment by sylvaindurand** [comment]
That would be great! Is there some documentation?

**Comment by DirtyF** [comment]
You could take a look at: https://github.com/jekyll/jekyll/blob/57ccbe08ea8553e31d4234380277865a3d6569ad/site/_docs/themes.md

Parker also mentionned an upcoming command to ease the creation of theme: https://talk.jekyllrb.com/t/packaging-themes/2279/2

**Comment by sylvaindurand** [comment]
[Done!](https://rubygems.org/gems/jekyll-multilingual)

I follow the docs but I didn't try anything as Jekyll doesn't provide theme support yet. I suppose I need to include parts of `_config.yml`, which I didn't yet. Please let me now if there is any problem in Jekyll development version.
