### ISSUE TITLE
Select language based on user's browser settings

### ISSUE THREAD

**Issue by AvtechScientific** [sylvaindurand/jekyll-multilingual#20]
Hello,

thank you for the useful example and explanation!

Is it possible to redirect user to his preferred language, based on his browser language setting (or maybe OS setting)? It should be done on start of the session (or the first visit) only, later if he manually switches to another language - that one should be preferred.

Maybe it can be done with javascript?...

**Comment by sylvaindurand** [comment]
It's really hard to do. Using Javascript could create unwanted, and painful, redirections for the user.
It is also possible to do this on the server side, but this requires settings that are not obvious.

As far as I'm concerned, as my users come from search engines, I trust Google to detect the user's language, and redirect them to the right version of my page.
