### ISSUE TITLE
Language Switcher showing irrelevant contents

### ISSUE THREAD

**Issue by anaclumos** [sylvaindurand/jekyll-multilingual#22]
First of all, thank you for the template.
I love this template, except for one crucial error in the file `jekyll-multilingual/_includes/header.html`.

I have figured that the following part creates language switching links. 

```HTML
<div class="wrapper" style="text-align: right; line-height: 2em">
  {% assign posts=site.posts | where:"ref", page.ref | sort: 'lang' %}
  {% for post in posts %} <a href="{{ post.url | prepend: site.baseurl }}"
class="{{ post.lang }}">{{ post.lang }}</a> {% endfor %}

  {% assign pages=site.pages | where:"ref", page.ref | sort: 'lang' %}
  {% for page in pages %} <a href="{{ page.url | prepend: site.baseurl }}"
class="{{ page.lang }}">{{ page.lang }}</a> {% endfor %}
</div>
```
However, it pulls the entire list of posts and pages and displays them.

Which leads to this problem:
<img width="999" alt="screen shot 2018-10-22 at 7 10 13 pm" src="https://user-images.githubusercontent.com/31657298/47287956-f27e4000-d62e-11e8-81ed-aab453413a3a.png">
Please check the upper right corner, at the language switcher. 

I figured this issue is currently happening on the master branch of the code. I have not modified any code, only `copy-paste`d the posts several times (three times, to be precise.)

Users will expect the language switcher to only show the toggle to show the same post in a different language. Furthermore, showing several "en"s and "fr"s confuses the user :(

Other than that, I love the template. Fixing this bug will make this the Number 1 multi-lang Jekyll template!
Thank you for reading, and have a nice day :)

**Comment by cpence** [comment]
This will occur if pages have duplicated "ref" values, which probably happened if you copy-pasted the posts. You'll have to make sure that the "ref" values for every page are unique.

**Comment by anaclumos** [comment]
This solved my problem! Thank you 👍
