### ISSUE TITLE
Strategy for linking between posts

### ISSUE THREAD

**Issue by aguadopd** [sylvaindurand/jekyll-multilingual#8]
Hello Sylvain,

How do you suggest an automated way of linking between pages? Links should link to the right language of the post. For example, at the bottom of [this entry](https://www.sylvaindurand.org/ameliorer-la-typographie-sous-jekyll/) in your blog you link to another entry: `https://www.sylvaindurand.org/rendre-jekyll-multilingue/` . However, the English version of the same post links to `https://www.sylvaindurand.org/making-jekyll-multilingual/ `. Is that automated?

The web [I'm trying to translate](https://github.com/aguadopd/turtlebot-tutorial/tree/modificaciones) is linking like this: `[plugged in the Keurig]({{ site.url }}{% post_url 2015-02-01-27 %})`, which converts to `[base]/2015/02/01/27/`. `2015-02-01-27` is the name of the post file. 

For the Spanish version, the post filename is `2015-02-01-27_es`. Manually, `[plugged in the Keurig]({{ site.url }}{% post_url 2015-02-01-27_es %})` works but I was thinking on somehow inserting the underscore and the language tag into `{% post_url 2015-02-01-27 %}`. But maybe there is a better way..

If useful, 
```
# Build settings
markdown: kramdown
permalink: pretty
```

**Comment by sylvaindurand** [comment]
Hello! Nothing is automated. While writing my article, I manually write links in Markdown... 
I didn't try to use `{% post_url xxx %}`, I'll try to find out what is possible. Please let me know if something works for you ;)

**Comment by sylvaindurand** [comment]
I confirm that there is no *Liquid* syntax simpler than your need. It is possible to find automatically the translation with loops (for lang icons in a navigation bar for example) but it would be quite verbose  for a simple link in an article...
