### ISSUE TITLE
Support for pagination

### ISSUE THREAD

**Issue by rodrigoescandon** [sylvaindurand/jekyll-multilingual#9]
Sylvain,

As far as I can tell, there is no support for pagination in your example. Have you implemented it in any ways? Do you have any plans of doing so or any ideas?

I tried moving the translated index file to a subfolder and modifying the "paginate_path" parameter, but then it stops generating pagination for the main parameter –it only allows one "paginate_path".

**Comment by sylvaindurand** [comment]
You're not the first to ask! I didn't try but I'll take some time to have a look. Please tell me if you find something ;)

**Comment by bradonomics** [comment]
I've been poking at this for a few days also, trying to get pagination working for the secondary language. So far I've found nothing that works. I found [this tutorial](http://anjesh.github.io/2015/01/25/collection-pagination-working-github-pages/) which is working to get prev/next links inside the articles.

**Comment by fenollp** [comment]
Would something like https://github.com/leaiov/portfolio/blob/gh-pages/_includes/modal.html#L14-L16 help?

**Comment by sylvaindurand** [comment]
Showing **prev/next links** isn't that difficult: as always, we simply need to loop!

Prev:
```
{% for post in site.posts %}
  {% if post.lang == page.lang %}
    {% if prev %}
      {{ post.id }}
    {% endif %}
    {% assign prev = false %}
    {% if post.id == page.id %}
      {% assign prev = true %}
    {% endif %}
  {% endif %}
{% endfor %}
```

Next:
```
{% for post in site.posts reversed %}
  {% if post.lang == page.lang %}
    {% if next %}
      <a href="{{ post.url }}">next</a>
      {% break %}
    {% endif %}
    {% assign next = false %}
    {% if post.id == page.id %}
      {% assign next = true %}
    {% endif %}
  {% endif %}
{% endfor %}
```

I'll add those two samples of code in my article. 

Concerning **pagination**, this feature as been requested several times but... I can't find a way to make it works. There is no way to generate multiple pages (/1/, /2/, /3/...) from a single page or layout with Jekyll without a plugin. Or, the “official” pagination plugin doesn't even support tags or categories...
